#!/bin/bash

SESSION_NAME=$1


# Check if the session already exists
if tmux has-session -t $SESSION_NAME 2>/dev/null; then
    echo "Session $SESSION_NAME already exists. Attaching to it."
    tmux attach-session -t $SESSION_NAME
else
    # Create a new session and name it
    tmux new-session -d -s $SESSION_NAME

    # Split the window horizontally
    tmux split-window -v
    
    #tmux resize-pane -D 

    tmux swap-pane -D
    tmux swap-pane -D


    tmux split-window -h

   
    tmux send-keys -t 0 'htop' C-m
    tmux send-keys -t 1 'watch -n 1 sensors' C-m
    tmux send-keys -t 2 'watch -n 1 cpupower -c 3 frequency-info' C-m

    # Attach to the created session
    tmux attach-session -t $SESSION_NAME
fi
